# Generated by Django 3.1 on 2020-08-21 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='description',
            new_name='name',
        ),
    ]
